### ISSUE TITLE
Doesn't add all pages to graph

### ISSUE THREAD

**Issue by iw2bab27** [iheyunfei/no-graph#1]
Not sure if its because I have too many pages (100s of pages) - but doesn't show all pages connected to a dot 
For example:
![image](https://user-images.githubusercontent.com/91477152/140914514-274f4009-7332-44d2-95f2-f01b622c8d2e.png)
![image](https://user-images.githubusercontent.com/91477152/140914542-b76c9885-33fd-4882-b7a4-b7ae43ddb0ee.png)

**Comment by hyfdev** [comment]
The current implementation isn't in the right direction. I'm considering refacotring it using official API, but I'm too busy to do it now.

**Comment by iw2bab27** [comment]
no worries
